- alias: "[Дополнительный свет (Зал)] - Переключать состояние Philips в зале через MQTT"
  id: toggle_livingroom_philips
  trigger:
    - platform: mqtt
      topic: "livingroom/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: homeassistant.toggle
      target:
        entity_id: group.livingroon_color_lights
    - delay: 0.5
    - service: mqtt.publish
      data:
        topic: "livingroom/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('group.livingroon_color_lights') }}\"}"
         
- alias: "[Дополнительный свет (Зал)] - Включать состояние Philips в зале через MQTT"
  id: on_livingroom_philips
  trigger:
    - platform: mqtt
      topic: "livingroom/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "ON"
      encoding: "utf-8"
  action:
    - service: homeassistant.turn_on
      target:
        entity_id: group.livingroon_color_lights
    - delay: 0.5
    - service: mqtt.publish
      data:
        topic: "livingroom/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('group.livingroon_color_lights') }}\"}"
        
- alias: "[Дополнительный свет (Зал)] - Выключать состояние Philips в зале через MQTT"
  trigger:
    - platform: mqtt
      topic: "livingroom/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "OFF"
      encoding: "utf-8"
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: group.livingroon_color_lights
    - delay: 2
    - service: mqtt.publish
      data:
        topic: "livingroom/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('group.livingroon_color_lights') }}\"}"
        
###########################

- alias: "[Основной свет (Бар)] - Переключать состояние Philips в баре через MQTT"
  id: toggle_bar_philips
  trigger:
    - platform: mqtt
      topic: "bar/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: homeassistant.toggle
      target:
        entity_id: group.bar_lights_color
    - delay: 0.5
    - service: mqtt.publish
      data:
        topic: "bar/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('group.bar_lights_color') }}\"}"
         
- alias: "[Основной свет (Бар)] - Включать состояние Philips в баре через MQTT"
  id: on_bar_philips
  trigger:
    - platform: mqtt
      topic: "bar/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "ON"
      encoding: "utf-8"
  action:
    - service: homeassistant.turn_on
      target:
        entity_id: group.bar_lights_color_color
    - delay: 0.5
    - service: mqtt.publish
      data:
        topic: "bar/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('group.bar_lights_color') }}\"}"
        
- alias: "[Основной свет (Бар)] - Выключать состояние Philips в баре через MQTT"
  trigger:
    - platform: mqtt
      topic: "bar/livingroom/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "OFF"
      encoding: "utf-8"
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: group.bar_lights_color
    - delay: 2
    - service: mqtt.publish
      data:
        topic: "bar/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('group.bar_lights_color') }}\"}"